### ISSUE TITLE
HDRbatch not being "installed" in linux

### ISSUE THREAD

**Issue by fjavifabre** [wkjarosz/hdrview#116]
CMake installs hdrbatch binary in Windows but not in Linux (I do not know if this is this intended behavior). It would be nice to fix this using the following line in CMakeLists.txt (Line 555) for Linux too:

`install(TARGETS hdrbatch RUNTIME DESTINATION "bin")`

**Comment by wkjarosz** [comment]
Thanks for the bug report. This isn't intentional, i just don't have a linux box to test on. I'll add your fix.
