### ISSUE TITLE
Any chance of Windows binaries for v2.0.0-beta.2? Can I compile v2.0.0-beta.2 for Windows manually?

### ISSUE THREAD

**Issue by futuremotiondev** [wkjarosz/hdrview#122]
My question is the title of the thread. On the releases page here: https://github.com/wkjarosz/hdrview/releases/tag/v2.0.0-beta.2, there is only a `.dmg` for download.

Is it possible to obtain or build windows binaries for the beta?

I have CMake / Visual Studio / Etc.

Thanks for any info.

**Comment by wkjarosz** [comment]
I haven't yet had a chance to debug this myself, and my experience with windows development is limited. If you have the equipment and experience, I am happy to accept contributions that help get us some binaries. A good starting point would be the github actions https://github.com/wkjarosz/hdrview/blob/dear-imgui/.github/workflows/release.yml and https://github.com/wkjarosz/hdrview/blob/dear-imgui/.github/workflows/ci-windows.yml, both of which have my half-working attempt at getting things to build on windows.

**Comment by wkjarosz** [comment]
Version 2 has been released and should work on Windows.
