### ISSUE TITLE
Request: add option to always fit image to window size.

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [wkjarosz/hdrview#124]
This will be helpful if we are comparing images with different resolutions. Right now we have to press F every time we switch the image, to fit the image to window size. 

Thanks

**Comment by wkjarosz** [comment]
Sounds like a useful feature. Happy to take a pull request if I don't get to this soon enough for you.

**Comment by wkjarosz** [comment]
This feature is now available in the master branch, and will be included in the next release. There are options to fit the display window or the data window. You can go to https://wkjarosz.github.io/hdrview/dev/ to see it in action.
