### ISSUE TITLE
logging verbosity

### ISSUE THREAD

**Issue by MangoSister** [wkjarosz/hdrview#57]
Hello,

First, I am a big fan of hdrview. I think it's a really good tool to compare exr/hdr images.

At latest master (3a9689c), the logging seems to become overly verbose if I hold the mouse button down and drag the image around (screenshot):
![Capture](https://user-images.githubusercontent.com/4036119/123880011-a400c380-d8f6-11eb-8487-07988033b0ea.PNG)
I am not sure exactly when it started to happen, but should be after the project migrated from bitbucket.
Is it possible to add a flag to adjust the verbosity, or simply remove this kind of spammy logs?

Thanks!

**Comment by wkjarosz** [comment]
Hi!

There is indeed already a verbosity flag. Just pass e.g. --verbosity=2. Run --help for more info. I changed the default to 0 while I develop.

**Comment by wkjarosz** [comment]
> Hello,
> 
> First, I am a big fan of hdrview. I think it's a really good tool to compare exr/hdr images.
> 
> At latest master ([3a9689c](https://github.com/wkjarosz/hdrview/commit/3a9689c5f0177661088843cf4b0a17e727fc8843)), the logging seems to become overly verbose if I hold the mouse button down and drag the image around (screenshot):
> ![Capture](https://user-images.githubusercontent.com/4036119/123880011-a400c380-d8f6-11eb-8487-07988033b0ea.PNG)
> I am not sure exactly when it started to happen, but should be after the project migrated from bitbucket.
> Is it possible to add a flag to adjust the verbosity, or simply remove this kind of spammy logs?
> 
> Thanks!

FYI @MangoSister : In the newest v1.4 release I’ve set the default verbosity back to info or higher, and the setting is saved in the config file (which can be overridden by the —verbosity command line flag).

**Comment by MangoSister** [comment]
@wkjarosz Glad to know that. Thank you so much for adding this!
