### ISSUE TITLE
Color3/Color4::min()/max() conflict with macros in <windows.h> on Windows

### ISSUE THREAD

**Issue by MangoSister** [wkjarosz/hdrview#79]
Hi,

The latest build seems to be broken on windows because the `min()/max()` member of `Color3/Color4` conflicts with the macros in `<windows.h>`. One simple fix could be to define `NOMINMAX` for windows, e.g.
```
if(WIN32)
  target_compile_definitions(HDRView PRIVATE -DNOMINMAX)
endif()
```
Thanks!

**Comment by wkjarosz** [comment]
Thanks. Yes, I'm working on it. I already have a pull request that hopefully also fixes the windows GitHub actions for continuous integration. Hopefully will be pushed to master in the next couple days.

**Comment by MangoSister** [comment]
Ok. good to know. I will use the above fix for my local build at the meantime.
