### ISSUE TITLE
Build fails due to linker error

### ISSUE THREAD

**Issue by kunaltyagi** [wkjarosz/hdrview#88]
Encountered a linker error during source build on master

Issue seems to be missing `Imath_2_5::SingleMatrixExc` and other symbols from OpenEXR targets
[install.log](https://github.com/wkjarosz/hdrview/files/9257758/install.log)

**Comment by wkjarosz** [comment]
I assume this is on Linux? The GitHub action seems to compile fine on Linux, so you could compare how you configured/built to how it is set up in the ci-linux.yml workflow. I’m afraid I don’t have access to a Linux machine handy, but am open to pull requests if you are able to track down the issue.

**Comment by kunaltyagi** [comment]
This isn't an issue with my setup. I replicated the issue 100% same logs in a fresh docker image of `ubuntu:22.04`
```sh
apt udpate
apt install -y g++ cmake xorg-dev libglu1-mesa-dev zlib1g-dev libxrandr-dev
```

Except g++, rest all are from the CI config. Following the readme instructions after this setup results in the error. Docker works on windows, so you can replicate the issue there, and the setup and base image are simple and common

**Comment by wkjarosz** [comment]
@kunaltyagi I think this is related to #14. Can you check whether running cmake config twice like in:

https://github.com/wkjarosz/hdrview/blob/master/.github/workflows/ci-linux.yml

Fixes your issue?

Thanks.

**Comment by wkjarosz** [comment]
I believe #94 fixes this. If not, please create a new issue.
