### ISSUE TITLE
support for depth image

### ISSUE THREAD

**Issue by LogWell** [wkjarosz/hdrview#90]
The [cvkit](https://github.com/roboception/cvkit) can display the raw values stored in the depth image, how to set it up in hdrview (it seems to be normalized)
![image](https://user-images.githubusercontent.com/34391447/190080681-c05955af-a59c-4f71-b2ce-d6f6716d66aa.png)

**Comment by wkjarosz** [comment]
HDRView is currently primarily intended for rgba images. I haven't ever tried to load depth images personally, so am not even sure what it does when faced with such an image. This is a limiation, which would be great to lift at some point, but solving it well would require a significant rework of how HDRView stores and maintains image channels.

Maybe for depth images it's possible to special-case the loader and viewer code. I would welcome a pull request with such an improvement if it can be done elegantly and unobtrusively.

**Comment by wkjarosz** [comment]
Closing this issue for now, but please submit a pull request if you are able to fix this. Thanks.
