### ISSUE TITLE
The same file cannot be opened in another location

### ISSUE THREAD

**Issue by LogWell** [wkjarosz/hdrview#91]
**Can be opened** hdrview '/home/lab0/Pictures/SimpleAlbedo.png' 
**Can't be opened** hdrview '/media/lab0/NaGenHao/SimpleAlbedo.png' 
*NaGenHao* is another SSD.

![SimpleAlbedo](https://user-images.githubusercontent.com/34391447/192713218-585f9c05-b455-4f4d-9767-64b72571cf07.png)

![image](https://user-images.githubusercontent.com/34391447/192713741-8f685d95-d2bc-4ebc-89d6-624ced6ef410.png)

**Comment by wkjarosz** [comment]
Interesting. This would be hard for me to reproduce. Can you build in debug mode and run through a debugger? That could help us identify the root of the problem.
